# config/routes.yaml
# test:
#     path: /test
#     # the controller value has the format 'controller_class::method_name'
#     controller: TyCode\Product\Infrastructure\Web\Other\Other::test

    # if the action is implemented as the __invoke() method of the
    # controller class, you can skip the '::method_name' part:
    # controller: App\Controller\BlogController