<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNSYmMWZ\TyCode_ms_Seller_SellerKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNSYmMWZ/TyCode_ms_Seller_SellerKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNSYmMWZ.legacy');

    return;
}

if (!\class_exists(TyCode_ms_Seller_SellerKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNSYmMWZ\TyCode_ms_Seller_SellerKernelDevDebugContainer::class, TyCode_ms_Seller_SellerKernelDevDebugContainer::class, false);
}

return new \ContainerNSYmMWZ\TyCode_ms_Seller_SellerKernelDevDebugContainer([
    'container.build_hash' => 'NSYmMWZ',
    'container.build_id' => '4d8a70fc',
    'container.build_time' => 1706485094,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNSYmMWZ');
