<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUx6xq0T\TyCode_ms_Seller_SellerKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUx6xq0T/TyCode_ms_Seller_SellerKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUx6xq0T.legacy');

    return;
}

if (!\class_exists(TyCode_ms_Seller_SellerKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUx6xq0T\TyCode_ms_Seller_SellerKernelDevDebugContainer::class, TyCode_ms_Seller_SellerKernelDevDebugContainer::class, false);
}

return new \ContainerUx6xq0T\TyCode_ms_Seller_SellerKernelDevDebugContainer([
    'container.build_hash' => 'Ux6xq0T',
    'container.build_id' => '12fea4e6',
    'container.build_time' => 1706426387,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUx6xq0T');
