<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'product_search_get' => [['id'], ['_controller' => 'TyCode\\ms\\Seller\\Controller\\Product\\GetProduct'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/seller/product']], [], [], []],
    'product_search_all_get' => [[], ['_controller' => 'TyCode\\ms\\Seller\\Controller\\Product\\GetProducts'], [], [['text', '/seller/products']], [], [], []],
    'product_search_by_criteria_get' => [[], ['_controller' => 'TyCode\\ms\\Seller\\Controller\\Product\\GetProductByCriteria'], [], [['text', '/seller/product-by-criteria']], [], [], []],
    'review_create_post' => [[], ['_controller' => 'TyCode\\ms\\Seller\\Controller\\Review\\PostReviewCreate'], [], [['text', '/seller/review']], [], [], []],
    'seller_health_check_get' => [[], ['_controller' => 'TyCode\\ms\\Seller\\Controller\\HealthCheckGetController'], [], [['text', '/seller/health-check']], [], [], []],
];
