<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'seller_health_check_get' => [[], ['_controller' => 'TyCode\\Seller\\Product\\Infrastructure\\Web\\HealthCheckGetController'], [], [['text', '/product-health-check']], [], [], []],
    'product_search_get' => [['id'], ['_controller' => 'TyCode\\Seller\\Product\\Infrastructure\\Web\\GetProduct'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product']], [], [], []],
    'product_search_all_get' => [[], ['_controller' => 'TyCode\\Seller\\Product\\Infrastructure\\Web\\GetProducts'], [], [['text', '/products']], [], [], []],
    'product_search_by_criteria_get' => [[], ['_controller' => 'TyCode\\Seller\\Product\\Infrastructure\\Web\\GetProductByCriteria'], [], [['text', '/product-by-criteria']], [], [], []],
    'review_create_post' => [[], ['_controller' => 'TyCode\\Seller\\Review\\Infrastructure\\Web\\PostReviewCreate'], [], [['text', '/review']], [], [], []],
    'review_health_check_get' => [[], ['_controller' => 'TyCode\\Seller\\Review\\Infrastructure\\Web\\HealthCheckGetController'], [], [['text', '/review-health-check']], [], [], []],
];
