###
GET http://172.28.5.98:8000/product-health-check

###
GET http://172.28.5.98:8000/product/1eb6d1e2-1806-4812-ae88-d351cca8a6cb

###
GET http://172.28.5.98:8000/products

###
http://172.28.5.98:8000/product-by-criteria?operator[gt]=price:400.0&operator[not_in]=name:Samsumg A13

###
http://172.28.5.98:8000/product-by-criteria?id=1eb6d1e2-1806-4812-ae88-d351cca8a6cb

###
POST http://172.28.5.98:8000/product
Content-Type: application/json

{
    "id": "8ab56334-6a53-4b66-8b52-5cbbaecfdc93",
    "name": "Redmi Note 13 Pro",
    "price": 350.50,
    "images": [
        "localhost/image1",
        "localhost/image2",
        "localhost/image3"
    ],
    "stockQuantity": 50
}