<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLapp3uR\TyCode_ms_Product_ProductKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLapp3uR/TyCode_ms_Product_ProductKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLapp3uR.legacy');

    return;
}

if (!\class_exists(TyCode_ms_Product_ProductKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLapp3uR\TyCode_ms_Product_ProductKernelDevDebugContainer::class, TyCode_ms_Product_ProductKernelDevDebugContainer::class, false);
}

return new \ContainerLapp3uR\TyCode_ms_Product_ProductKernelDevDebugContainer([
    'container.build_hash' => 'Lapp3uR',
    'container.build_id' => 'ee6e5136',
    'container.build_time' => 1703635312,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLapp3uR');
