services:
  # Databases
  Doctrine\ORM\EntityManager:
    factory: [ 'TyCode\Product\Shared\Infrastructure\Doctrine\ProductEntityManagerFactory', 'create' ]
    arguments:
      - driver: '%env(PRODUCT_DATABASE_DRIVER)%'
        host: '%env(PRODUCT_DATABASE_HOST)%'
        port: '%env(PRODUCT_DATABASE_PORT)%'
        dbname: '%env(PRODUCT_DATABASE_NAME)%'
        user: '%env(PRODUCT_DATABASE_USER)%'
        password: '%env(PRODUCT_DATABASE_PASSWORD)%'
      - '%env(APP_ENV)%'
    tags:
      - { name: tycode.database_connection }
    public: true


  # Product
  TyCode\Product\Domain\Product\ProductRepository: '@TyCode\Product\Infrastructure\Persistence\DoctrineProductRepository'
