<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG25fl5C\TyCode_ms_Shop_ShopKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG25fl5C/TyCode_ms_Shop_ShopKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG25fl5C.legacy');

    return;
}

if (!\class_exists(TyCode_ms_Shop_ShopKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG25fl5C\TyCode_ms_Shop_ShopKernelDevDebugContainer::class, TyCode_ms_Shop_ShopKernelDevDebugContainer::class, false);
}

return new \ContainerG25fl5C\TyCode_ms_Shop_ShopKernelDevDebugContainer([
    'container.build_hash' => 'G25fl5C',
    'container.build_id' => 'b881cd74',
    'container.build_time' => 1704860408,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG25fl5C');
