<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUiLL25I\TyCode_ms_Shop_ShopKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUiLL25I/TyCode_ms_Shop_ShopKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUiLL25I.legacy');

    return;
}

if (!\class_exists(TyCode_ms_Shop_ShopKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUiLL25I\TyCode_ms_Shop_ShopKernelDevDebugContainer::class, TyCode_ms_Shop_ShopKernelDevDebugContainer::class, false);
}

return new \ContainerUiLL25I\TyCode_ms_Shop_ShopKernelDevDebugContainer([
    'container.build_hash' => 'UiLL25I',
    'container.build_id' => '90ae69e3',
    'container.build_time' => 1703713624,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUiLL25I');
