<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR8dUv9E\TyCode_ms_Shop_ShopKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR8dUv9E/TyCode_ms_Shop_ShopKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR8dUv9E.legacy');

    return;
}

if (!\class_exists(TyCode_ms_Shop_ShopKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR8dUv9E\TyCode_ms_Shop_ShopKernelDevDebugContainer::class, TyCode_ms_Shop_ShopKernelDevDebugContainer::class, false);
}

return new \ContainerR8dUv9E\TyCode_ms_Shop_ShopKernelDevDebugContainer([
    'container.build_hash' => 'R8dUv9E',
    'container.build_id' => 'b7480d36',
    'container.build_time' => 1703743772,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR8dUv9E');
