<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'product_create_post' => [[], ['_controller' => 'TyCode\\Shop\\Product\\Infrastructure\\Web\\PostProductCreate'], [], [['text', '/product']], [], [], []],
    'product_create_cqrs_post' => [[], ['_controller' => 'TyCode\\Shop\\Product\\Infrastructure\\Web\\PostProductCreateCQRS'], [], [['text', '/product-cqrs']], [], [], []],
    'product_health_check_get' => [[], ['_controller' => 'TyCode\\Shop\\Product\\Infrastructure\\Web\\HealthCheckGetController'], [], [['text', '/product-health-check']], [], [], []],
    'product_search_get' => [['id'], ['_controller' => 'TyCode\\Shop\\Product\\Infrastructure\\Web\\GetProduct'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product']], [], [], []],
    'product_search_all_get' => [[], ['_controller' => 'TyCode\\Shop\\Product\\Infrastructure\\Web\\GetProducts'], [], [['text', '/products']], [], [], []],
    'product_search_by_criteria_get' => [[], ['_controller' => 'TyCode\\Shop\\Product\\Infrastructure\\Web\\GetProductByCriteria'], [], [['text', '/product-by-criteria']], [], [], []],
    'product_search_by_criteria_cqrs_get' => [[], ['_controller' => 'TyCode\\Shop\\Product\\Infrastructure\\Web\\GetProductByCriteriaCQRS'], [], [['text', '/product-by-criteria-cqrs']], [], [], []],
    'review_health_check_get' => [[], ['_controller' => 'TyCode\\Shop\\Review\\Infrastructure\\Web\\HealthCheckGetController'], [], [['text', '/review-health-check']], [], [], []],
];
