# controllers:
#     resource:
#         path: ../../../../src/Seller/Product/Infrastructure/Web/
#         namespace: TyCode\Seller\Product\Infrastructure\Web
#     type: attribute

# kernel:
#     resource: TyCode\ms\Seller\SellerKernel
#     type: attribute