###
GET http://172.28.5.98:8000/seller/health-check

###
POST http://172.28.5.98:8000/seller/review
Content-Type: application/json

{
    "id": "1de9a843-d4e8-4698-8561-eda3e591b161",
    "productId": "8ab56334-6a53-4b66-8b52-5cbbaecfdc93",
    "author": "@ray",
    "message": "Redmi Note 13 Pro is a the best..."
}
